# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-Axigen
version:      0.09
version_from: lib/Net/Axigen.pm
installdirs:  site
requires:
    Net::Telnet:                   3.03

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
